### ISSUE TITLE
Warning: At least one frame is missing the time attribute.

### ISSUE THREAD

**Issue by YumYumYumi** [JohMast/rtsVis#1]
I used function rtsVis::ts_makeframes based on SRTM data and I keep getting warning "Warning: At least one frame is missing the time attribute." and I cannot add  "moveVis::add_timestamps(type = "label") %>%  moveVis::add_progress()" anymore. 

I want to make an animation about deforestation area which background is SRTM. The changed deforestation area will be expressed with my polygons. 

#######################################################
r_frames <- rtsVis::ts_makeframes(x_list = rom_interpolated_srtm,
                                  r_type = "gradient") 
Warning: At least one frame is missing the time attribute.

**Comment by YumYumYumi** [comment]
How can I change the alpha of hillshade from the function ts_makeframes? default is 0.5 but I want to increase it. 

########################################################################
r_frames<- rtsVis::ts_makeframes(x_list = rom_crop_filled_interpolated_2,
                                  l_indices = c(1,2,3),
                                  minq = 0.05,
                                  maxq = 0.9,
                                 hillshade = SRTM)

**Comment by JohMast** [comment]
> 
> 
> How can I change the alpha of hillshade from the function ts_makeframes? default is 0.5 but I want to increase it.
> 
> ########################################################################
> r_frames<- rtsVis::ts_makeframes(x_list = rom_crop_filled_interpolated_2,
> l_indices = c(1,2,3),
> minq = 0.05,
> maxq = 0.9,
> hillshade = SRTM)

It should have been possible to pass alpha as a parameter to ts_makeframes, but that did not work due to a bug that is now fixed. I hope that solves your problem!

**Comment by JohMast** [comment]
> 
> 
> I used function rtsVis::ts_makeframes based on SRTM data and I keep getting warning "Warning: At least one frame is missing the time attribute." and I cannot add "moveVis::add_timestamps(type = "label") %>% moveVis::add_progress()" anymore.
> 
> I want to make an animation about deforestation area which background is SRTM. The changed deforestation area will be expressed with my polygons.
> 
> #######################################################
> r_frames <- rtsVis::ts_makeframes(x_list = rom_interpolated_srtm,
> r_type = "gradient")
> Warning: At least one frame is missing the time attribute.


Curious, what do you get when you check the frames using the following?
`rtsVis:::.ts_get_frametimes(rom_interpolated_srtm)`
